# Generated by Django 3.1.6 on 2021-02-10 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20210204_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='mpa_rate',
            field=models.ForeignKey(blank=True, default='Not Rated', null=True, on_delete=django.db.models.deletion.PROTECT, to='films.score_mpa'),
        ),
    ]
