# Generated by Django 3.1.6 on 2021-02-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20210210_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
