# Generated by Django 3.1.6 on 2021-02-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20210210_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='mpa_rate',
            field=models.ForeignKey(blank=True, default='Not Rated', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='films.score_mpa'),
        ),
    ]
