# Generated by Django 3.1.6 on 2021-02-19 00:34

from django.db import migrations, models
import films.models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20210213_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_pic',
            field=models.ImageField(default='posters/<django.db.models.fields.AutoField>/poster.jpg', upload_to=films.models.poster_directory_path),
        ),
    ]
