# Generated by Django 3.1.6 on 2021-02-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_auto_20210220_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='Searchdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_clicked', to='films.film')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_term', to='films.search')),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='films',
            field=models.ManyToManyField(related_name='search_hits', through='films.Searchdata', to='films.Film'),
        ),
    ]
