# Generated by Django 3.1.6 on 2021-03-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20210224_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='enemy',
            field=models.ManyToManyField(blank=True, related_name='_country_enemy_+', to='films.Country'),
        ),
    ]
