# Generated by Django 3.1.6 on 2021-03-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_country_enemy'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='enemy_is',
            field=models.BooleanField(default=0),
        ),
    ]
