# Generated by Django 3.1.6 on 2021-03-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_country_enemy_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='_country_friend_+', to='films.Country'),
        ),
    ]
