# Generated by Django 3.1.6 on 2021-03-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_country_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='enemy_is',
            new_name='interest_is',
        ),
        migrations.AddField(
            model_name='country',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='_country_interest_+', to='films.Country'),
        ),
    ]
