# Generated by Django 3.1.6 on 2021-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_auto_20210304_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='enemy',
            field=models.ManyToManyField(blank=True, related_name='enemies_of', to='films.Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='friends_of', to='films.Country'),
        ),
    ]
