# Generated by Django 3.1.6 on 2021-03-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_auto_20210304_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='enemy',
        ),
        migrations.RemoveField(
            model_name='country',
            name='friend',
        ),
    ]
