# Generated by Django 3.1.6 on 2021-03-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_auto_20210304_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='dup',
            field=models.BooleanField(default=0),
        ),
    ]
