# Generated by Django 3.1.6 on 2021-03-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0022_auto_20210307_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/TRAPPIST-1e_Const_CMYK_Print.png/166px-TRAPPIST-1e_Const_CMYK_Print.png', max_length=500, null=True),
        ),
    ]
