# Generated by Django 3.1.6 on 2021-03-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_auto_20210307_0045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film_aka',
        ),
    ]
