# Generated by Django 3.1.6 on 2021-03-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0025_delete_film_aka'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2018-11-20T15:58:44.767594-06:00'),
            preserve_default=False,
        ),
    ]
