# Generated by Django 3.1.6 on 2021-03-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0026_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_about', to='films.film'),
        ),
    ]
