# Generated by Django 3.1.6 on 2021-03-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0027_auto_20210309_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='by',
            new_name='bya',
        ),
    ]
