# Generated by Django 3.1.6 on 2021-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0028_auto_20210316_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='bs_indicator',
        ),
        migrations.AddField(
            model_name='film',
            name='alt_tt_1',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='alt_tt_2',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='down_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='recs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='up_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
