# Generated by Django 3.1.6 on 2021-03-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0030_dummyfilm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyFilm',
        ),
    ]
