# Generated by Django 3.1.6 on 2021-03-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0031_delete_dummyfilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='net_alert',
            field=models.IntegerField(blank=True, choices=[(2, 'Not Film'), (0, 'No Access'), (1, 'All Good')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='net_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
