# Generated by Django 3.1.6 on 2021-03-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0032_auto_20210319_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='bechdel',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='co2_t',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
