# Generated by Django 3.1.6 on 2021-03-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0033_auto_20210320_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='emoji_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='emoji_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
