# Generated by Django 3.1.6 on 2021-03-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0034_auto_20210325_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='emoji_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='emoji_4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
