# Generated by Django 3.1.6 on 2021-03-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0035_auto_20210327_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='bechdel',
        ),
        migrations.AddField(
            model_name='film',
            name='down_bech',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='up_bech',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
