# Generated by Django 3.1.6 on 2021-03-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0036_auto_20210328_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='down_country',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='up_country',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
