# Generated by Django 3.1.6 on 2021-03-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0037_auto_20210328_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-year']},
        ),
    ]
