# Generated by Django 3.1.6 on 2021-04-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0042_auto_20210409_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='active',
            field=models.BooleanField(default=0),
        ),
    ]
