# Generated by Django 3.1.6 on 2021-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0043_collection_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=72, unique=True),
        ),
    ]
