# Generated by Django 3.1.5 on 2021-01-31 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        ('users', '0003_kubs_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bucket_list',
            field=models.ManyToManyField(blank=True, related_name='bucket_list', to='films.Film'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.ManyToManyField(blank=True, default="''", to='films.Country'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fav_films',
            field=models.ManyToManyField(blank=True, related_name='fav_film', to='films.Film'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='projector',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='projector', to='users.market'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='purpose',
            field=models.TextField(default='For me, films are a way to...'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_models',
            field=models.ManyToManyField(blank=True, to='films.Person'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seat',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='seat', to='users.market'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='speaker',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='speaker', to='users.market'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theatre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='theatre', to='users.market'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theatre_name',
            field=models.TextField(default='My Theatre'),
        ),
        migrations.DeleteModel(
            name='Kubs',
        ),
    ]
