# Generated by Django 3.1.5 on 2021-02-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210131_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='svg_link',
            field=models.CharField(default='users/market/chair_1.svg', max_length=100),
        ),
    ]
