# Generated by Django 3.1.5 on 2021-02-02 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        ('users', '0010_auto_20210202_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_from', to=settings.AUTH_USER_MODEL)),
                ('status', models.ManyToManyField(to='films.Film')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='recommend',
            field=models.ManyToManyField(related_name='recommending_to', through='users.Recommend', to=settings.AUTH_USER_MODEL),
        ),
    ]
