# Generated by Django 3.1.5 on 2021-02-03 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210202_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='status',
            new_name='films',
        ),
    ]
