# Generated by Django 3.1.6 on 2021-02-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210205_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='projector',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='theatre',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
    ]
