# Generated by Django 3.1.6 on 2021-02-07 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20210207_2058'),
        ('users', '0014_auto_20210207_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projector',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='projector', to='market.market'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seat',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='seat', to='market.market'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='speaker',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='speaker', to='market.market'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theatre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='theatre', to='market.market'),
        ),
    ]
