# Generated by Django 3.1.6 on 2021-02-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210209_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
