# Generated by Django 3.1.6 on 2021-02-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20210220_1647'),
        ('users', '0020_audience_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='popcorn',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.PROTECT, related_name='popcorn', to='market.market'),
        ),
    ]
