# Generated by Django 3.1.6 on 2021-02-20 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_customuser_popcorn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
