# Generated by Django 3.1.6 on 2021-02-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210220_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='theatre_name',
            field=models.CharField(default='My Theatre', max_length=60),
        ),
    ]
