# Generated by Django 3.1.6 on 2021-02-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210221_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='theatre',
            new_name='stage',
        ),
    ]
