# Generated by Django 3.1.6 on 2021-02-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210222_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='message',
            field=models.TextField(blank=True, default='Yo, you should probably watch this!'),
        ),
    ]
