# Generated by Django 3.1.6 on 2021-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_auto_20210224_1515'),
        ('users', '0029_customuser_searches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='searches',
            field=models.ManyToManyField(blank=True, to='films.Search'),
        ),
    ]
