# Generated by Django 3.1.6 on 2021-02-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20210224_1518'),
        ('users', '0030_auto_20210224_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='searches',
            field=models.ManyToManyField(blank=True, to='films.Searchdata'),
        ),
    ]
