# Generated by Django 3.1.6 on 2021-03-01 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20210224_1518'),
        ('users', '0032_film_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='recommend',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='films',
        ),
        migrations.AddField(
            model_name='recommend',
            name='film',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='rec_movie', to='films.film'),
            preserve_default=False,
        ),
    ]
