# Generated by Django 3.1.6 on 2021-03-02 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20210224_1518'),
        ('users', '0033_auto_20210301_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='Lemme know if this helps!')),
                ('points', models.IntegerField(choices=[(1, 'Do Not Think Of Watching'), (2, 'Nononono'), (3, 'Gonna Regret It'), (4, 'There Are Better Things To Watch'), (5, 'Meh'), (6, 'Go For It'), (7, 'Nice Pick'), (8, 'Great Pick'), (9, 'You Will Love This'), (10, 'Best Film You Will Ever Watch')])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_movie', to='films.film')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_from', to=settings.AUTH_USER_MODEL)),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
