# Generated by Django 3.1.6 on 2021-03-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20210224_1518'),
        ('users', '0034_freviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Freviews',
            new_name='Freview',
        ),
    ]
