# Generated by Django 3.1.6 on 2021-03-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210303_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kn',
            field=models.IntegerField(default=0),
        ),
    ]
