# Generated by Django 3.1.6 on 2021-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0027_auto_20210309_2359'),
        ('users', '0038_customuser_kn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='former_bucket',
            field=models.ManyToManyField(blank=True, related_name='rip_bucket', to='films.Film'),
        ),
    ]
