# Generated by Django 3.1.6 on 2021-03-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_customuser_former_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='checked',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='film_feedback',
            name='resolved',
            field=models.BooleanField(default=0),
        ),
    ]
