# Generated by Django 3.1.6 on 2021-03-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20210316_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='by',
            new_name='bya',
        ),
        migrations.RenameField(
            model_name='film_feedback',
            old_name='by',
            new_name='bya',
        ),
    ]
