# Generated by Django 3.1.6 on 2021-03-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20210317_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyfilm',
            name='new_film',
            field=models.BooleanField(default=0),
        ),
    ]
