# Generated by Django 3.1.6 on 2021-03-23 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0033_auto_20210320_1947'),
        ('users', '0047_auto_20210322_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('categ', models.IntegerField(blank=True, choices=[(1, 'Made Rec'), (2, 'Acc Friend'), (3, 'Sent Friend'), (4, 'Watched'), (5, 'Add Fav'), (6, 'Add Buck'), (7, 'Add Coll'), (8, 'Upg Theatre'), (9, 'Upg Speaker'), (10, 'Upg Seat'), (11, 'Upg Projector'), (12, 'Upg Popcorn')], null=True)),
                ('rel_collection', models.ManyToManyField(blank=True, to='users.User_Collection')),
                ('rel_films', models.ManyToManyField(blank=True, to='films.Film')),
                ('rel_users', models.ManyToManyField(blank=True, related_name='about_me', to=settings.AUTH_USER_MODEL)),
                ('seen', models.ManyToManyField(blank=True, related_name='seen_by_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.ManyToManyField(blank=True, to='users.Action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_action', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
