# Generated by Django 3.1.6 on 2021-03-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20210323_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='categ',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'No'), (3, 'No'), (4, 'No'), (5, 'No'), (6, 'No'), (7, 'No'), (8, 'No'), (9, 'No'), (10, 'No'), (11, 'No'), (12, 'No')], null=True),
        ),
    ]
