# Generated by Django 3.1.6 on 2021-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20210323_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='categ',
            field=models.IntegerField(choices=[(1, 'Made Rec'), (2, 'Acc Friend'), (3, 'Sent Friend'), (4, 'Watched'), (5, 'Add Fav'), (6, 'Add Buck'), (7, 'Add Coll'), (8, 'Upg Theatre'), (9, 'Upg Speaker'), (10, 'Upg Seat'), (11, 'Upg Projector'), (12, 'Upg Popcorn')], null=True),
        ),
        migrations.AlterField(
            model_name='actionid',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='by_user_id', to='users.Action'),
        ),
    ]
