# Generated by Django 3.1.6 on 2021-03-25 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_remove_user_collection_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_collection',
            old_name='name',
            new_name='collection_name',
        ),
    ]
