# Generated by Django 3.1.6 on 2021-03-28 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20210325_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_collection',
            name='copied_by',
            field=models.ManyToManyField(blank=True, related_name='copied_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
