# Generated by Django 3.1.6 on 2021-03-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_collection_copied_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_collection',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
