# Generated by Django 3.1.6 on 2021-04-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_dummyfilm_co2_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_collection',
            name='time_built',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
