# Generated by Django 3.1.6 on 2021-04-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_user_collection_time_built'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ab_groups',
            field=models.CharField(default='1', max_length=17),
        ),
    ]
