# Generated by Django 3.1.6 on 2021-04-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_customuser_ab_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ab_groups',
        ),
    ]
