# Generated by Django 3.1.6 on 2021-04-02 15:56

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_customuser_ab_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ab_groups',
            field=models.CharField(default=users.models.bi_string, max_length=17),
        ),
    ]
