# Generated by Django 3.1.6 on 2021-04-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_auto_20210402_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='trailer_time_seconds',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
