# Generated by Django 3.1.6 on 2021-03-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0038_auto_20210331_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('follow_count', models.IntegerField(default=0)),
                ('copy_count', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('privacy', models.IntegerField(choices=[(0, 'Private'), (1, 'Public'), (2, 'Friends')], default=1)),
                ('films', models.ManyToManyField(to='films.Film')),
                ('tags', models.ManyToManyField(blank=True, related_name='deleted_collection_tags', to='films.Tag')),
            ],
        ),
    ]
