# Generated by Django 3.1.6 on 2021-04-01 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleted_collection',
            name='former_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deleted_collection',
            name='time_created',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='deleted_collection',
            name='time_deleted',
            field=models.TimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
