# Generated by Django 3.1.6 on 2021-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='svg',
        ),
        migrations.AlterField(
            model_name='market',
            name='svg_link',
            field=models.CharField(default='market/icons/chair_1.svg', max_length=100),
        ),
    ]
