# Generated by Django 3.1.6 on 2021-02-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210211_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='categ',
            field=models.IntegerField(blank=True, choices=[(0, 'Theatre'), (1, 'Projector'), (2, 'Speaker'), (3, 'Popcorn'), (4, 'Seat')]),
        ),
    ]
