# Generated by Django 3.1.6 on 2021-02-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_market_svg_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='svg_next',
        ),
    ]
