# Generated by Django 3.1.6 on 2021-02-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_market_svg_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='level_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.market'),
        ),
    ]
