# Generated by Django 3.1.6 on 2021-02-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_market_level_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('hover_time', models.ManyToManyField(blank=True, to='market.Citation')),
                ('replies', models.ManyToManyField(blank=True, related_name='_comment_replies_+', to='market.Comment')),
            ],
        ),
    ]
