# Generated by Django 3.1.6 on 2021-03-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='title',
        ),
        migrations.AddField(
            model_name='meta',
            name='title_id',
            field=models.CharField(default='summer', max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meta',
            name='title_print',
            field=models.CharField(default='sin', max_length=70),
            preserve_default=False,
        ),
    ]
