# Generated by Django 3.1.6 on 2021-04-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20210313_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='hide_bot',
            field=models.BooleanField(default=0),
        ),
    ]
