# Generated by Django 3.1.6 on 2021-04-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_meta_hide_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meta',
            old_name='description',
            new_name='text',
        ),
    ]
