# Generated by Django 3.1.6 on 2021-04-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_auto_20210401_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
