# Generated by Django 3.1.6 on 2021-03-17 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tribe.models
import users


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0031_delete_dummyfilm'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.collection_directory_path)),
                ('privacy', models.IntegerField(choices=[(0, 'Private'), (1, 'Public'), (2, 'Friends')], default=1)),
                ('bya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_creator', to=settings.AUTH_USER_MODEL)),
                ('films', models.ManyToManyField(to='films.Film')),
                ('followers', models.ManyToManyField(blank=True, related_name='collection_followers', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='collection_tags', to='films.Tag')),
            ],
        ),
    ]
