# Generated by Django 3.1.6 on 2021-03-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0002_auto_20210317_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Collection',
        ),
    ]
